version: "3.7"

services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/code
      - /client/node_modules
    command: npm run start
    links:
      - backend
    networks:
      - sessionauthnetwork

  backend:
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - ./:/code
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - sessionauthnetwork

  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sessionauthnetwork

volumes:
  mongodb:
  mongodb_config:

networks:
  sessionauthnetwork:
    driver: bridge
