version: "3.7"

services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    container_name: session-auth-client
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/code
      - /code/node_modules
    stdin_open: true
    links:
      - api
    networks:
      - sessionauthnetwork

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    container_name: session-auth-api
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/code
      - /code/node_modules
    depends_on:
      - mongo
    networks:
      - sessionauthnetwork

  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sessionauthnetwork

volumes:
  mongodb:
  mongodb_config:

networks:
  sessionauthnetwork:
    driver: bridge
